# Bandit configuration
exclude_dirs:
  - .git
  - .venv
  - venv
  - dist
  - build
  - .mypy_cache
  - .pytest_cache

skips:
  - B101   # assert used
  - B603   # subprocess call with shell=True
  - B607   # subprocess call without shell=True
# Bandit configuration
exclude_dirs:
  - .git
  - .venv
  - venv
  - dist
  - build
  - .mypy_cache
  - .pytest_cache

skips:
  - B101   # assert used
  - B603   # subprocess call with shell=True
  - B607   # subprocess call without shell=True
